# Generated by Django 5.0.14 on 2025-10-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_feedback_approved_by_remove_feedback_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='demo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
