# Generated by Django 5.0.14 on 2025-10-06 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_solution_demo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='event_name',
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='core.event'),
        ),
    ]
