# Generated by Django 5.0.14 on 2025-10-07 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_galleryitem_event_name_galleryitem_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='title',
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to='core.event'),
        ),
        migrations.CreateModel(
            name='GalleryItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('gallery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.galleryitem')),
            ],
        ),
    ]
