# Generated by Django 5.0.14 on 2025-10-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_galleryitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
    ]
