# Generated by Django 5.2.10 on 2026-06-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_event_is_promoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='slogan',
            field=models.CharField(default='Weaving Innovation Beyond Expectations', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default='About PyLoom', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='PyLoom', max_length=100),
        ),
    ]
