# Generated by Django 5.2.10 on 2026-06-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sitesettings_slogan_alter_aboutus_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
    ]
