# Generated by Django 5.2.14 on 2026-06-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_category_dynamic_solution_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Optional canonical URL if this content has a preferred external URL.'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Optional SEO description. Recommended: 150-160 characters.'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Optional SEO title. Recommended: 50-60 characters.', max_length=70),
        ),
        migrations.AddField(
            model_name='article',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Optional social sharing image.', null=True, upload_to='seo/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Optional canonical URL if this content has a preferred external URL.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Optional SEO description. Recommended: 150-160 characters.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Optional SEO title. Recommended: 50-60 characters.', max_length=70),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Optional social sharing image.', null=True, upload_to='seo/'),
        ),
        migrations.AddField(
            model_name='event',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Optional canonical URL if this content has a preferred external URL.'),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Optional SEO description. Recommended: 150-160 characters.'),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Optional SEO title. Recommended: 50-60 characters.', max_length=70),
        ),
        migrations.AddField(
            model_name='event',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Optional social sharing image.', null=True, upload_to='seo/'),
        ),
        migrations.AddField(
            model_name='project',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Optional canonical URL if this content has a preferred external URL.'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Optional SEO description. Recommended: 150-160 characters.'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Optional SEO title. Recommended: 50-60 characters.', max_length=70),
        ),
        migrations.AddField(
            model_name='project',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Optional social sharing image.', null=True, upload_to='seo/'),
        ),
        migrations.AddField(
            model_name='solution',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Optional canonical URL if this content has a preferred external URL.'),
        ),
        migrations.AddField(
            model_name='solution',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Optional SEO description. Recommended: 150-160 characters.'),
        ),
        migrations.AddField(
            model_name='solution',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Optional SEO title. Recommended: 50-60 characters.', max_length=70),
        ),
        migrations.AddField(
            model_name='solution',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Optional social sharing image.', null=True, upload_to='seo/'),
        ),
    ]
