# Generated by Django 5.2.13 on 2026-06-27 12:43

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_project_slug_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='certificate',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='training',
            name='class_schedule',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='training',
            name='delivery_mode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='training',
            name='learning_outcomes',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='training',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20),
        ),
    ]
