# Generated by Django 5.2.13 on 2026-06-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_training_certificate_training_class_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
