# Generated by Django 5.2.13 on 2026-06-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_training_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='canonical_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='solution',
            name='meta_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='solution',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AddField(
            model_name='solution',
            name='og_image',
            field=models.ImageField(blank=True, default='', upload_to='solutions/'),
        ),
    ]
