# Generated by Django 5.2.14 on 2026-07-25 05:05

from django.db import migrations, models


def add_event_canonical_url_if_missing(apps, schema_editor):
    Event = apps.get_model('core', 'Event')
    table_name = Event._meta.db_table
    column_name = 'canonical_url'

    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor,
                table_name,
            )
        }

    if column_name in existing_columns:
        return

    field = models.URLField(blank=True, default='')
    field.set_attributes_from_name(column_name)
    schema_editor.add_field(Event, field)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_careervacancy'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_event_canonical_url_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='event',
                    name='canonical_url',
                    field=models.URLField(blank=True, default=''),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop'), ('webinar', 'Webinar'), ('showcase', 'Showcase'), ('symposium', 'Symposium'), ('training', 'Training')], max_length=20),
        ),
        migrations.AlterField(
            model_name='solution',
            name='canonical_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
