# Generated by Django 5.2.14 on 2026-07-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_careervacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='canonical_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop'), ('webinar', 'Webinar'), ('showcase', 'Showcase'), ('symposium', 'Symposium'), ('training', 'Training')], max_length=20),
        ),
        migrations.AlterField(
            model_name='solution',
            name='canonical_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
