# Generated by Codex on 2026-07-25

from django.db import migrations, models


def add_event_meta_description_if_missing(apps, schema_editor):
    Event = apps.get_model('core', 'Event')
    table_name = Event._meta.db_table
    column_name = 'meta_description'

    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor,
                table_name,
            )
        }

    if column_name in existing_columns:
        return

    field = models.TextField(blank=True, default='')
    field.set_attributes_from_name(column_name)
    schema_editor.add_field(Event, field)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_event_canonical_url_alter_event_event_type_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_event_meta_description_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='event',
                    name='meta_description',
                    field=models.TextField(blank=True, default=''),
                ),
            ],
        ),
    ]
