# Generated by Codex on 2026-07-25

from django.db import migrations, models


def backfill_event_canonical_url(apps, schema_editor):
    Event = apps.get_model('core', 'Event')
    Event.objects.filter(canonical_url__isnull=True).update(canonical_url='')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_event_meta_description'),
    ]

    operations = [
        migrations.RunPython(
            backfill_event_canonical_url,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='event',
            name='canonical_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
