# Generated by Codex on 2026-07-25

from django.db import migrations, models


def existing_column_names(schema_editor, table_name):
    with schema_editor.connection.cursor() as cursor:
        return {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor,
                table_name,
            )
        }


def add_event_seo_fields_if_missing(apps, schema_editor):
    Event = apps.get_model('core', 'Event')
    table_name = Event._meta.db_table
    existing_columns = existing_column_names(schema_editor, table_name)

    fields = [
        ('meta_title', models.CharField(max_length=70, blank=True, default='')),
        ('og_image', models.ImageField(upload_to='events/', blank=True, default='')),
    ]

    for column_name, field in fields:
        if column_name in existing_columns:
            continue
        field.set_attributes_from_name(column_name)
        schema_editor.add_field(Event, field)


def backfill_event_seo_fields(apps, schema_editor):
    Event = apps.get_model('core', 'Event')
    table_name = schema_editor.quote_name(Event._meta.db_table)
    meta_title = schema_editor.quote_name('meta_title')
    og_image = schema_editor.quote_name('og_image')

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f'UPDATE {table_name} SET {meta_title} = %s WHERE {meta_title} IS NULL', [''])
        cursor.execute(f'UPDATE {table_name} SET {og_image} = %s WHERE {og_image} IS NULL', [''])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_event_canonical_url_not_null'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_event_seo_fields_if_missing,
                    migrations.RunPython.noop,
                ),
                migrations.RunPython(
                    backfill_event_seo_fields,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='event',
                    name='meta_title',
                    field=models.CharField(blank=True, default='', max_length=70),
                ),
                migrations.AddField(
                    model_name='event',
                    name='og_image',
                    field=models.ImageField(blank=True, default='', upload_to='events/'),
                ),
            ],
        ),
    ]
