# Generated by Codex on 2026-07-25

from django.db import migrations, models


def existing_column_names(schema_editor, table_name):
    with schema_editor.connection.cursor() as cursor:
        return {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor,
                table_name,
            )
        }


def add_event_seo_fields_if_missing(apps, schema_editor):
    Event = apps.get_model('core', 'Event')
    table_name = Event._meta.db_table
    existing_columns = existing_column_names(schema_editor, table_name)

    missing_columns = []
    if 'meta_title' not in existing_columns:
        missing_columns.append(
            "ALTER TABLE %(table)s ADD COLUMN %(column)s varchar(70) NOT NULL DEFAULT ''"
            % {
                'table': schema_editor.quote_name(table_name),
                'column': schema_editor.quote_name('meta_title'),
            }
        )
    if 'og_image' not in existing_columns:
        missing_columns.append(
            "ALTER TABLE %(table)s ADD COLUMN %(column)s varchar(100) NOT NULL DEFAULT ''"
            % {
                'table': schema_editor.quote_name(table_name),
                'column': schema_editor.quote_name('og_image'),
            }
        )

    if missing_columns:
        with schema_editor.connection.cursor() as cursor:
            for sql in missing_columns:
                cursor.execute(sql)


def backfill_event_seo_fields(apps, schema_editor):
    Event = apps.get_model('core', 'Event')
    table_name = schema_editor.quote_name(Event._meta.db_table)
    meta_title = schema_editor.quote_name('meta_title')
    og_image = schema_editor.quote_name('og_image')

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"UPDATE {table_name} SET {meta_title} = '' WHERE {meta_title} IS NULL")
        cursor.execute(f"UPDATE {table_name} SET {og_image} = '' WHERE {og_image} IS NULL")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_event_canonical_url_not_null'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_event_seo_fields_if_missing,
                    migrations.RunPython.noop,
                ),
                migrations.RunPython(
                    backfill_event_seo_fields,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='event',
                    name='meta_title',
                    field=models.CharField(blank=True, default='', max_length=70),
                ),
                migrations.AddField(
                    model_name='event',
                    name='og_image',
                    field=models.ImageField(blank=True, default='', upload_to='events/'),
                ),
            ],
        ),
    ]
