# Generated by Django 5.2.10 on 2026-08-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_clientpartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpartner',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
