# Generated by Django 5.2.10 on 2026-08-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_clientpartner_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='canonical_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
